# yaml-language-server: $schema=https://storage.googleapis.com/coderabbit_public_assets/schema.v2.json

language: en-US
tone_instructions: ''
early_access: false
enable_free_tier: true

reviews:
  profile: chill
  request_changes_workflow: false
  high_level_summary: true
  high_level_summary_placeholder: '@coderabbitai summary'
  high_level_summary_in_walkthrough: false
  auto_title_placeholder: '@coderabbitai'
  auto_title_instructions: ''
  review_status: true
  commit_status: true
  fail_commit_status: false
  collapse_walkthrough: false
  changed_files_summary: true
  sequence_diagrams: true
  estimate_code_review_effort: true
  assess_linked_issues: true
  related_issues: true
  related_prs: true
  suggested_labels: true
  auto_apply_labels: false
  suggested_reviewers: true
  auto_assign_reviewers: false
  poem: true
  labeling_instructions: []

  # Exclude non-source code directories from reviews
  path_filters:
    - '!deployment/**'
    - '!dev-ops/**'
    - '!release-notes/**'
    - '!src/api-doc/**'
    - '!src/assets/**'
    - '!src/configs/**'
    - '!src/public/**'
    - '!src/temp/**'
    - '!**/*.md'

  # Add specific review instructions for critical paths
  path_instructions:
    - path: 'src/services/**'
      instructions: 'This is core business logic. Please check for correctness, efficiency, and potential edge cases.'
    - path: 'src/controllers/**'
      instructions: 'These are API controllers. Focus on request/response handling, security (auth middleware usage), and proper status codes.'
    - path: 'src/database/queries/**'
      instructions: 'Review database queries for performance. Check for N+1 problems and ensure indexes can be used.'
    - path: 'src/validators/**'
      instructions: 'Validate all incoming data thoroughly. Check for missing or incomplete validation rules.'
    - path: 'src/middlewares/**'
      instructions: 'This is security-sensitive middleware. Scrutinize for potential vulnerabilities.'

  abort_on_close: true
  disable_cache: false

  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: ['WIP', 'skip-review']
    labels: []
    drafts: false
    # Regular reviews: all PRs into develop
    base_branches:
      - 'develop'

  finishing_touches:
    docstrings:
      enabled: true
    unit_tests:
      enabled: true

  pre_merge_checks:
    docstrings:
      mode: warning
      threshold: 80
    title:
      mode: warning
      requirements: ''
    description:
      mode: warning
    issue_assessment:
      mode: warning

  tools:
    eslint: { enabled: true }
    semgrep: { enabled: true }
    dotenvLint: { enabled: true }
    sqlfluff: { enabled: true }
    checkov: { enabled: true }
    gitleaks: { enabled: true }
    hadolint: { enabled: true }
    shellcheck: { enabled: true }
    actionlint: { enabled: true }
    circleci: { enabled: true }
    github-checks: { enabled: true }
    markdownlint: { enabled: true }
    yamllint: { enabled: true }
    biome: { enabled: true }
    languagetool: { enabled: false }
    ast-grep:
      essential_rules: true
      rule_dirs: []
      util_dirs: []
      packages: []

# --- NEW: PR-specific changelog generation for staging merges ---
changelog:
  enabled: true
  base_branches:
    - 'develop'
  instructions: |
    For PRs merging into `staging`, generate a **QA-focused changelog** using only the diff files in this PR:

    1. Provide **detailed bullet points** of all changes relevant to QA:
       - Updated or new endpoints in `controllers`
       - Business logic in `services`
       - Database changes (migrations, models, queries)
       - Config/constant changes
       - Helpers/middlewares
    2. End each section with clear action points for QA testing.
    3. After the detailed list, write a **compact QA summary (1–2 paragraphs)** suitable for Jira/Slack.
    4. Keep changelog strictly PR-specific — do not include unrelated history.

chat:
  auto_reply: true
  integrations:
    jira:
      usage: auto
    linear:
      usage: auto

knowledge_base:
  opt_out: false
  web_search:
    enabled: true
  code_guidelines:
    enabled: true
    filePatterns: []
  learnings:
    scope: auto
  issues:
    scope: auto
  jira:
    usage: auto
    project_keys: []
  linear:
    usage: auto
    team_keys: []
  pull_requests:
    scope: auto

code_generation:
  docstrings:
    language: en-US
    path_instructions: []
  unit_tests:
    path_instructions: []
